" ~./vimrc

set nocompatible
filetype off 
let s:path = substitute($HOME . '/.vim/bundle/Vundle.vim', '/', has('win32' ) ? '\\' : '/', 'g')
execute 'set rtp+=' . s:path

call vundle#begin()
  Plugin 'VundleVim/Vundle.vim'
  Plugin 'lifepillar/vim-solarized8'
  " Plugin 'plasticboy/vim-markdown'
call vundle#end()

" au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

" Tel vim terminal support true / 24 bit / RGB  colors
if has('termguicolors') && (&term == 'screen-256color' || &term == 'tmux-256color' || &term == 'xterm-256color')
  set termguicolors
  if exists('$TMUX')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  endif
endif

set background=dark
autocmd vimenter * ++nested colorscheme solarized8
                                                   
" highlight htmlBold gui=bold guifg=#af0000 ctermfg=214 cterm=bold
" highlight htmlItalic gui=italic guifg=#ff8700 ctermfg=214 cterm=italic

" let g:markdown_syntax_conceal = 3
set conceallevel=3 
let g:markdown_fenced_languages = ['c++=cpp', 'viml=vim', 'bash=sh', 'fortran' ]

syntax enable
   

